# Generated by Django 5.0.6 on 2024-07-02 23:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator])),
                ('intensity', models.IntegerField(default=None, null=True)),
                ('sector', models.CharField(default=None, max_length=255, null=True)),
                ('topic', models.CharField(max_length=255, null=True)),
                ('insight', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('region', models.CharField(max_length=255, null=True)),
                ('start_year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator])),
                ('impact', models.CharField(max_length=255, null=True)),
                ('added', models.CharField(max_length=255, null=True)),
                ('published', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('relevance', models.CharField(max_length=255, null=True)),
                ('pestle', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('likelihood', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
