# Generated by Django 5.0.6 on 2024-06-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.DateTimeField(null=True)),
                ('intensity', models.IntegerField(null=True)),
                ('sector', models.TextField(null=True)),
                ('topic', models.CharField(max_length=255, null=True)),
                ('insight', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('region', models.CharField(max_length=255, null=True)),
                ('start_year', models.DateTimeField(null=True)),
                ('impact', models.CharField(max_length=255, null=True)),
                ('added', models.DateTimeField(null=True)),
                ('published', models.DateTimeField(null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('relevance', models.CharField(max_length=255, null=True)),
                ('pestle', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('likelihood', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
