# Generated by Django 5.0.6 on 2024-06-30 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='added',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='end_year',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator]),
        ),
        migrations.AlterField(
            model_name='info',
            name='intensity',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='sector',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='start_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator]),
        ),
    ]
