# Generated by Django 5.0.6 on 2024-07-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_info_added_alter_info_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='added',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
